export const strings = {
  appName: 'NimTzyAgent',

  common: {
    cancel: 'Cancel',
    save: 'Save',
    delete: 'Delete',
    rename: 'Rename',
    retry: 'Retry',
    dismiss: 'Dismiss',
    close: 'Close',
    done: 'Done',
    copy: 'Copy',
    copied: 'Copied',
    edit: 'Edit',
    stop: 'Stop',
    undo: 'Undo',
    search: 'Search',
    none: 'None',
    notAvailable: 'Not available',
    back: 'Back',
    add: 'Add',
    ok: 'OK',
    apply: 'Apply',
    clear: 'Clear',
  },

  onboarding: {
    tagline: 'A chat client for the DeepSeek API. Your key stays on this device.',
    apiKeyLabel: 'API key',
    apiKeyPlaceholder: 'sk-...',
    baseUrlLabel: 'Base URL',
    testConnection: 'Test connection',
    testing: 'Testing connection',
    continueLabel: 'Start using NimTzyAgent',
    missingKey: 'Enter an API key to continue.',
    help: 'Create a key in the DeepSeek console, then paste it here. It is stored in the device keychain and never leaves this device except in requests to the API.',
  },

  conversations: {
    title: 'Chats',
    newChat: 'New chat',
    emptyTitle: 'No conversations yet',
    emptyBody: 'Start a chat and it will appear here.',
    searchPlaceholder: 'Search messages',
    noResults: 'No messages match that search.',
    deleteTitle: 'Delete conversation',
    deleteBody: 'This removes the conversation and its messages from this device.',
    deleted: 'Conversation deleted',
    renameTitle: 'Rename conversation',
    pin: 'Pin',
    unpin: 'Unpin',
    exportMarkdown: 'Export as Markdown',
    exportJson: 'Export as JSON',
    exportEmpty: 'This conversation has nothing to export yet.',
    exportTitle: 'Export conversation',
    renameLabel: 'Title',
    renamePlaceholder: 'Conversation title',
    searchHint: 'Search across every conversation.',
    searchResultCount: (count: number) => (count === 1 ? '1 result' : `${count} results`),
  },

  chat: {
    placeholder: 'Message',
    send: 'Send',
    stop: 'Stop generating',
    thinking: 'Reasoning',
    thinkingFor: (seconds: number) => `Thought for ${seconds}s`,
    reasoningHidden: 'Reasoning',
    regenerate: 'Regenerate',
    editMessage: 'Edit and resend',
    editWarning: 'Everything after this message will be removed.',
    deleteMessage: 'Delete message',
    stopped: 'Stopped',
    failed: 'Failed',
    scrollToBottom: 'Scroll to bottom',
    emptyTitle: 'No messages yet',
    emptyBody: 'Send the first message to begin.',
    estimatedCost: 'Estimated cost',
    model: 'Model',
    attachImage: 'Image',
    attachFile: 'File',
    takePhoto: 'Camera',
    photoLibrary: 'Photo library',
    attachTitle: 'Add attachment',
    attachments: 'Attachments',
    removeAttachment: 'Remove attachment',
    visionRequired: 'The selected model has no vision support. Switch models to send images.',
    switchModel: 'Switch model',
    imageTooLarge: 'That image is larger than 32 MB.',
    fileTooLarge: 'That file is larger than the 256 KB inline limit.',
    unsupportedFile: 'Only text-based files can be attached.',
    unreadableFile: 'That file could not be read.',
    attachFailed: 'The attachment could not be opened.',
    permissionDenied: 'Permission was not granted.',
    clipboardEmpty: 'The clipboard has no image.',
    noKey: 'Add an API key in Settings to send messages.',
    openSettings: 'Open settings',
    messageActions: 'Message',
    yourMessage: 'Your message',
    deleteMessageBody: 'The message is removed from this device.',
    copyText: 'Copy text',
    copyReasoning: 'Copy reasoning',
    pasteImage: 'Paste image',
    editTitle: 'Edit message',
    resend: 'Resend',
  },

  models: {
    title: 'Model',
    thinking: 'Thinking',
    vision: 'Vision',
    context: 'Context',
    legacy: 'Legacy',
    custom: 'Custom',
    addCustom: 'Add custom model',
    customIdLabel: 'Model ID',
    customIdPlaceholder: 'deepseek-...',
    customThinking: 'Supports thinking mode',
    customVision: 'Supports image input',
    customTools: 'Supports tools',
    noTools: 'No tools',
    switchedMidChat: 'The full conversation is resent to the new model on the next message.',
    removeCustom: 'Remove custom model',
  },

  presets: {
    title: 'System prompts',
    newPreset: 'New preset',
    nameLabel: 'Name',
    descriptionLabel: 'Description',
    bodyLabel: 'Prompt',
    bodyPlaceholder: 'You are a precise assistant. Answer in short paragraphs...',
    defaultLabel: 'Default for new chats',
    emptyTitle: 'No presets yet',
    emptyBody: 'A preset is a reusable system prompt. Create one to set how the model answers.',
    deleteTitle: 'Delete preset',
    deleteBody: 'Conversations using this preset fall back to the default.',
    duplicate: 'Duplicate',
    editTitle: 'Edit preset',
    nameRequired: 'Give the preset a name.',
  },

  research: {
    title: 'Web research',
    toggle: 'Research',
    provider: 'Search provider',
    providerLabel: {
      duckduckgo: 'DuckDuckGo',
      wikipedia: 'Wikipedia',
      serper: 'Serper',
    },
    providerHint: 'DuckDuckGo and Wikipedia need no key. Serper returns full web results and needs its own key.',
    serperKey: 'Serper key',
    serperKeyPlaceholder: 'Paste a Serper key',
    serperKeyHint: 'Stored in the device keychain, like the DeepSeek key.',
    keyRequired: 'Serper needs an API key. Add one in Settings, or pick another provider.',
    keyRejected: 'The search provider rejected the key.',
    rateLimited: 'The search provider is rate limiting this device. Try again shortly.',
    unreachable: 'The search provider could not be reached.',
    timedOut: 'The search request timed out.',
    failed: 'The search request failed.',
    unreadable: 'The search provider returned something unreadable.',
    emptyQuery: 'The search query was empty.',
    noResults: (query: string) => `No results for "${query}".`,
  },

  agent: {
    title: 'Agent',
    tools: 'Agent tools',
    toolsHint: 'Lets the model search the web and write files into a folder you choose.',
    workspace: 'Workspace folder',
    workspaceHint: 'Files are written only inside this folder. Nothing outside it can be touched.',
    choose: 'Choose folder',
    change: 'Change folder',
    forget: 'Forget folder',
    none: 'No folder chosen',
    needsFolder: 'Agent tools are on, but no folder is chosen, so file tools stay off.',
    accessLost: 'This folder can no longer be opened. Choose it again.',
    steps: 'Steps',
    arguments: 'Arguments',
    result: 'Result',
    /**
     * Sent as the system prompt whenever the file tools are on. The tool
     * definitions alone say what a tool can do, not that the model should
     * reach for it, and a chat model asked for a project will happily print
     * the code instead of writing it. This is the app saying which it wants.
     */
    filePreamble: (folder: string) =>
      [
        `File tools are on, and they write inside the workspace folder "${folder}" and nowhere else.`,
        'When the user asks for a file or a project, put it in the folder with write_file instead of printing it in your reply:',
        'one call per file, with the complete contents, and a path relative to the workspace root.',
        'write_file creates any missing parent folders itself, so create_folder is only for an empty folder.',
        'Never pass an absolute path and never include ".." in one.',
        'Once the files are written, reply with a short summary of what was written and how to open it,',
        'and leave the file contents out of the chat unless the user asks to see them.',
      ].join(' '),
    researchPreamble:
      'Web search is on. Use search_web for anything that may have changed since training — releases, prices, current events, documentation — and answer from what it returns.',
    folderLabel: (folder: string) => `Workspace: ${folder}`,
    stepRunning: 'Running',
    stepFailed: 'Failed',
    stopped: 'Stopped before this ran.',
    incompleteCall: 'The response ended before this call was complete.',
    toolSearch: 'Web search',
    toolFolder: 'Create folder',
    toolWrite: 'Write file',
    wrote: (path: string) => `Wrote ${path}`,
    made: (path: string) => `Created ${path}`,
    searched: (query: string) => `Searched "${query}"`,
    roundLimit: 'Stopped after several rounds of tool use.',
  },

  preview: {
    title: 'Preview',
    open: 'Preview',
    block: (index: number) => `Block ${index + 1}`,
    scriptedNote:
      'Scripts run inside this preview. It cannot reach your files or the rest of the app, and links inside it do not open.',
    empty: 'This message has no previewable HTML.',
    unavailable: 'The preview could not be opened.',
  },

  workspace: {
    defaultName: 'Selected folder',
    accessLost: 'The folder can no longer be opened. Pick it again in Settings.',
    badPath: (kind: string) =>
      `That ${kind} path was refused. Use a relative path inside the workspace folder, without "..".`,
    tooLarge: 'That file is too large to write in one step.',
    pickFailed: 'The folder picker could not be opened.',
    missing: 'Choose a workspace folder in Settings first.',
    check: 'Test folder',
    checkHint: 'Makes a folder and a file, rewrites the file, then removes both.',
    checkRun: 'Run',
    checkRunning: 'Testing',
    checkOk: 'The folder took a new folder, a new file, and a rewrite of that file.',
    checkOpen: 'opening the folder',
    checkFolder: 'creating a folder in it',
    checkWrite: 'writing a file into that folder',
    checkReplace: 'rewriting the file that was just written',
    checkFailed: (step: string) => `The test stopped at ${step}.`,
    checkLeftBehind: 'The test folder could not be removed, so it is still there.',
  },

  settings: {
    title: 'Settings',
    account: 'Connection',
    apiKeyLabel: 'API key',
    apiKeyPlaceholder: 'sk-...',
    baseUrlLabel: 'Base URL',
    baseUrlHint: 'Change only for a proxy or gateway.',
    testConnection: 'Test connection',
    testing: 'Testing',
    balanceNote: 'Requests are billed by DeepSeek to the account that owns this key.',
    generation: 'Generation',
    defaultModel: 'Default model',
    thinking: 'Thinking mode',
    thinkingHint: 'Reasoning runs before the answer and can be collapsed in the chat.',
    reasoningEffort: 'Reasoning effort',
    maxTokens: 'Maximum output tokens',
    maxTokensHint: 'Leave empty to use the model default.',
    systemPrompt: 'System prompt',
    systemPromptDefault: 'Default prompt',
    systemPromptHint:
      'Sent before every message in a new chat. A chat you set a preset on uses that preset instead.',
    systemPromptNone: 'Not set',
    presetsRow: 'Presets',
    presetsRowHint: 'Saved prompts, applied per chat.',
    appearance: 'Appearance',
    theme: 'Theme',
    themeSystem: 'System',
    themeDark: 'Dark',
    themeLight: 'Light',
    behaviour: 'Behaviour',
    haptics: 'Haptic feedback on send',
    streamResponses: 'Stream responses',
    data: 'Data',
    exportAll: 'Export all conversations',
    clearAll: 'Delete all conversations',
    clearAllTitle: 'Delete all conversations',
    clearAllBody: 'Every conversation and message on this device will be removed. This cannot be undone.',
    cleared: 'All conversations deleted',
    about: 'About',
    support: 'Support',
    supportTelegram: 'Telegram',
    supportFacebook: 'Facebook',
    supportEmail: 'Email',
    supportHint: 'Questions, bug reports, and feature requests.',
    supportFailed: 'Nothing on this device can open that link.',
    version: 'Version',
    apiDocs: 'DeepSeek API documentation',
    aboutBody: 'NimTzyAgent is a client for the DeepSeek API. It has no backend: requests go from this device to the API using your key.',
    keySaved: 'Connection saved',
    paramIgnoredThinking: 'Ignored while thinking mode is enabled.',
    shareUnavailable: 'Sharing is not available on this device.',
    keyReplaced: 'Replace key',
    keyCleared: 'Key removed from this device.',
    keyRequired: 'Enter a key before testing the connection.',
    clearKeyTitle: 'Remove API key',
    clearKeyBody: 'The key is deleted from the device keychain. Existing conversations stay.',
    reasoningLow: 'Low',
    reasoningHigh: 'High',
    reasoningMax: 'Max',
    reasoningHint: 'Low answers quickly. High is the default. Max spends the most on reasoning.',
    noKeySet: 'Not set',
    aboutTitle: 'About',
    aboutLegal: 'NimTzyAgent is not affiliated with DeepSeek.',
  },

  errors: {
    title: 'Something went wrong',
    offline: 'No connection',
    offlineBody: 'Messages cannot be sent until the connection returns.',
    timeout: 'The request timed out.',
    streamFailed: 'The response stopped before it finished.',
  },
} as const;
